In [1]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from loadTDMS import *
from fft_test import *
import numpy as np
from tqdm import tqdm

In [2]:
# Normalization class
mmsc=MinMaxScaler()
# Standardize class
stdsc = StandardScaler()

### how to handle 3d nparray
get items from list of 2d co-ordinates  
https://stackoverflow.com/questions/73369106/numpy-3d-array-get-items-from-a-list-of-2d-co-ordinates

In [187]:
img = np.random.randint(1,10,(3,10,8))
crds = np.array([[1,3], [2,2]])

In [188]:
img

array([[[9, 5, 9, 6, 3, 9, 3, 2],
        [8, 6, 4, 6, 2, 5, 1, 8],
        [2, 1, 1, 9, 1, 3, 2, 9],
        [9, 2, 2, 8, 2, 7, 3, 7],
        [5, 1, 5, 5, 4, 1, 5, 7],
        [9, 5, 5, 8, 4, 5, 2, 3],
        [9, 7, 7, 3, 9, 6, 1, 6],
        [9, 8, 1, 3, 4, 5, 2, 1],
        [8, 9, 8, 8, 5, 1, 2, 5],
        [7, 3, 5, 2, 6, 3, 5, 5]],

       [[8, 8, 7, 4, 5, 5, 2, 8],
        [2, 5, 5, 9, 6, 3, 9, 8],
        [8, 3, 1, 2, 2, 7, 3, 4],
        [4, 2, 5, 7, 5, 7, 5, 9],
        [9, 7, 4, 8, 8, 9, 2, 2],
        [5, 7, 7, 5, 6, 1, 3, 2],
        [5, 4, 1, 2, 2, 5, 2, 3],
        [4, 2, 6, 2, 8, 9, 3, 5],
        [3, 7, 2, 4, 2, 8, 2, 7],
        [7, 9, 5, 6, 1, 9, 9, 8]],

       [[4, 3, 2, 3, 2, 6, 9, 3],
        [1, 7, 9, 2, 4, 7, 2, 4],
        [4, 5, 2, 6, 3, 5, 6, 2],
        [5, 3, 3, 6, 5, 3, 4, 8],
        [8, 7, 5, 4, 7, 9, 1, 6],
        [8, 8, 5, 9, 4, 5, 4, 5],
        [3, 1, 9, 2, 5, 9, 1, 1],
        [2, 8, 1, 4, 3, 2, 3, 8],
        [7, 6, 3, 4, 7, 2, 9, 5],
        [5

In [189]:
img[crds[:,0],crds[:,1]]

array([[4, 2, 5, 7, 5, 7, 5, 9],
       [4, 5, 2, 6, 3, 5, 6, 2]])

In [264]:
d = np.load(rf"Z:\200 Produced_data\20230113+0117\FFT\spindle\121.npy")
d_n = d.reshape(1200,820)
d_n = d_n.reshape(1200,10,82)

In [265]:
fq = np.array([1,10])
fq = fq -1

In [266]:
d_n = d_n[:,[fq]]
d_n.shape

(1200, 1, 2, 82)

In [267]:
d_n = d_n.reshape(1200,82*len(fq))
d_n.shape

(1200, 164)

In [276]:
d_n = d_n.ravel()
d_n.shape

(196800,)

In [233]:
dd = np.load(rf"Z:\200 Produced_data\20230113+0117\train_data\TrainData_A_51-60path_spindle_200-300kHz\_TrainData_A_51-60path_spindle_200-300kHz.npy")

In [242]:
dd.shape

(1968000, 1)

In [275]:
1200*164*10

1968000

In [ ]:
d_nn[]

In [138]:
a = np.random.randint(1,10, (2,3,5))
a

array([[[8, 3, 9, 5, 2],
        [2, 1, 6, 5, 6],
        [5, 5, 9, 3, 8]],

       [[1, 1, 8, 2, 7],
        [8, 9, 2, 4, 7],
        [1, 5, 7, 7, 2]]])

In [149]:
a[0]

array([[8, 3, 9, 5, 2],
       [2, 1, 6, 5, 6],
       [5, 5, 9, 3, 8]])

In [154]:
crds = np.array([[1,3], [2,2]])

In [180]:
img = np.random.randint(1,10,(3,10,8))

In [181]:
img

array([[[3, 2, 2, 7, 1, 1, 4, 8],
        [6, 5, 5, 4, 9, 5, 3, 1],
        [1, 3, 5, 8, 4, 1, 9, 2],
        [4, 8, 2, 6, 5, 1, 8, 2],
        [6, 1, 9, 5, 7, 2, 2, 6],
        [5, 9, 1, 4, 6, 2, 3, 1],
        [4, 9, 3, 3, 3, 7, 1, 5],
        [4, 6, 9, 1, 8, 8, 3, 1],
        [6, 3, 1, 6, 9, 8, 4, 7],
        [4, 9, 6, 1, 7, 3, 9, 2]],

       [[2, 1, 3, 8, 4, 5, 1, 6],
        [4, 9, 5, 5, 9, 9, 2, 1],
        [1, 3, 7, 4, 1, 1, 2, 9],
        [6, 6, 7, 9, 1, 9, 4, 4],
        [6, 8, 2, 5, 1, 8, 7, 2],
        [1, 7, 7, 1, 8, 2, 5, 4],
        [5, 8, 3, 2, 7, 9, 1, 1],
        [1, 6, 1, 4, 7, 8, 1, 5],
        [7, 7, 2, 8, 4, 7, 3, 1],
        [6, 6, 8, 9, 4, 2, 1, 5]],

       [[5, 1, 8, 5, 8, 8, 9, 8],
        [4, 1, 5, 7, 6, 8, 2, 7],
        [3, 5, 3, 5, 7, 4, 5, 1],
        [3, 8, 2, 4, 5, 7, 2, 8],
        [7, 2, 1, 8, 5, 3, 3, 9],
        [9, 8, 2, 3, 1, 7, 2, 3],
        [8, 8, 7, 6, 4, 4, 3, 6],
        [7, 4, 9, 1, 6, 9, 9, 9],
        [8, 9, 9, 7, 5, 4, 4, 5],
        [1

In [176]:
crds[:,0]

array([1, 2])

In [177]:
crds[:,1]

array([3, 2])

In [185]:
fq = [0,1,2]

In [193]:
# img[crds[:,0],crds[:,1]]
img[:,[fq]]
# img[crds[:,0],crds[:,1]]

array([[[[9, 5, 9, 6, 3, 9, 3, 2],
         [8, 6, 4, 6, 2, 5, 1, 8],
         [2, 1, 1, 9, 1, 3, 2, 9]]],


       [[[8, 8, 7, 4, 5, 5, 2, 8],
         [2, 5, 5, 9, 6, 3, 9, 8],
         [8, 3, 1, 2, 2, 7, 3, 4]]],


       [[[4, 3, 2, 3, 2, 6, 9, 3],
         [1, 7, 9, 2, 4, 7, 2, 4],
         [4, 5, 2, 6, 3, 5, 6, 2]]]])

In [109]:
d_nn = d_n.reshape(1200,10,82)

## Select arguments
- tool : date
  - A : 20230113+0117
  - B : 20230120 
  - C : 20230123  
- path_range  
  ex) 51-60path  

- frequency
  ex) 200-300kHz
 
- AE_sensor_location
  - spindle
  - work

In [8]:
def make_trainD(case, tool, start, end, fq, AE_s_l):
    
    if tool == "A":
        date = "20230113+0117"
        interval = 1200
    if tool == "B":
        date = "20230120"
        interval = 1200
    if tool == "C":
        date = "20230123"
        interval = 1023
    
    d = np.array([])

    for i in range(start,end+1):
        d_n = np.load(rf"Z:\200 Produced_data\{date}\FFT\{AE_s_l}\{i}.npy")
        d_n = d_n.reshape(interval,820)
        d_n = d_n.reshape(interval,10,82)
        d_n = d_n[:,[fq]]
        d_n = d_n.reshape(interval,82*len(fq))
        d_n = d_n.ravel()
        d = np.append(d,d_n)
    
    d_stdsc = stdsc.fit_transform(d.reshape(-1,1))
    np.save(rf"Z:\200 Produced_data\MashineLearning\trainD\case{case}_{tool}",d_stdsc)
    np.save(rf"Z:\200 Produced_data\MashineLearning\trainD\case{case}_{tool}_mean",stdsc.mean_)
    np.save(rf"Z:\200 Produced_data\MashineLearning\trainD\case{case}_{tool}_std",np.sqrt(stdsc.var_))
    

    make_testD(case, tool, fq, AE_s_l)

In [9]:
def make_testD(case, tool, fq, AE_s_l):
    
    mean = np.load(rf"Z:\200 Produced_data\MashineLearning\trainD\case{case}_{tool}_mean.npy")
    std = np.load(rf"Z:\200 Produced_data\MashineLearning\trainD\case{case}_{tool}_std.npy")
    
    for test_tool in ["A","B","C"]:
        if test_tool == "A":
            date = "20230113+0117"
            interval = 1200
        if test_tool == "B":
            date = "20230120"
            interval = 1200
        if test_tool == "C":
            date = "20230123"
            interval = 1023
    
        d = np.array([])

        for i in tqdm(range(1,461)):
            d_n = np.load(rf"Z:\200 Produced_data\{date}\FFT\{AE_s_l}\{i}.npy")
            d_n = d_n.reshape(interval,820)
            d_n = d_n.reshape(interval,10,82)
            d_n = d_n[:,[fq]]
            d_n = d_n.reshape(interval,82*len(fq))
            d_n = d_n.ravel()
            d = np.append(d,d_n)

        test_stdsc = (d - mean) / std

        np.save(rf"Z:\200 Produced_data\MashineLearning\testD\case{case}_{test_tool}", test_stdsc)

In [10]:
%%time
fq = np.array([5,6])
fq = fq-1
a = make_trainD(1,"A",51,60,fq,"spindle")

100%|██████████| 460/460 [01:53<00:00,  4.05it/s]


Wall time: 6min 19s


In [23]:
case1_A = np.load(rf"Z:\200 Produced_data\MashineLearning\testD\case1_A.npy")
case1_B = np.load(rf"Z:\200 Produced_data\MashineLearning\testD\case1_B.npy")
case1_C = np.load(rf"Z:\200 Produced_data\MashineLearning\testD\case1_C.npy")

In [13]:
len(case1_A)

90528000

In [19]:
len(case1_C)/164

470580.0

In [24]:
%matplotlib qt
plt.plot(case1_B)

In [26]:
plt.plot(case1_B[:164])

In [27]:
train_d = np.load(rf"Z:\200 Produced_data\MashineLearning\trainD\case1_A.npy")

In [29]:
len(train_d)/164

12000.0